# Server
server.port=8081
server.servlet.context-path=/user-service-Linh

# Database
spring.datasource.url=jdbc:postgresql://26.169.181.65:5432/bankdb_sang
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=/dDMtv80KZSwPmYUT6r0Qj6LJNpSwCmwt7hqv0x5hc+RgNz3v6bFYVF3IrWjTsxLj//ddVXi34mNrEZ454nmGg==
jwt.expiration=86400000

# Logging
logging.level.com.bank.userservice=DEBUG
logging.level.org.springframework.security=DEBUG